<#
.SYNOPSIS
Writes sandbox-safe runtime configuration for a PR test environment.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [int]
    $PrNumber,

    [Parameter(Mandatory = $true)]
    [string]
    $SitePath,

    [Parameter(Mandatory = $true)]
    [string]
    $EnvironmentPath,

    [Parameter(Mandatory = $true)]
    [string]
    $SandboxConnectionString,

    [Parameter(Mandatory = $false)]
    [string]
    $SharedFileStorageRoot = "C:\RockTestEnvs\SharedStorage"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (!(Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

Ensure-Directory -Path $SitePath
Ensure-Directory -Path (Join-Path $SitePath "App_Data")
Ensure-Directory -Path (Join-Path $EnvironmentPath "Logs")
Ensure-Directory -Path (Join-Path $EnvironmentPath "Temp")
Ensure-Directory -Path $SharedFileStorageRoot

$connectionStringConfig = @"
<!-- Rock RMS PR test environment connection strings. Generated by Set-PrEnvironmentRuntimeConfiguration.ps1. -->
<connectionStrings>
  <add name="RockContext" connectionString="$SandboxConnectionString" providerName="System.Data.SqlClient" />
</connectionStrings>
"@
$connectionStringConfig | Out-File -FilePath (Join-Path $SitePath "web.ConnectionStrings.config") -Encoding UTF8 -Force

$webConfigPath = Join-Path $SitePath "web.config"
if (Test-Path $webConfigPath) {
    $publicRoot = "https://pr-$PrNumber.staging.connect.passion.team"
    $webConfig = Get-Content $webConfigPath -Raw
    $webConfig = $webConfig -replace '(<attributeValue\s+attributeKey="PublicApplicationRoot"[^>]*value=")"', "`${1}$publicRoot`""
    $webConfig | Out-File -FilePath $webConfigPath -Encoding UTF8 -Force
}

# Production integration credentials are intentionally not deployed to PR environments.
# The transform below overrides common outbound integration/app settings with inert values.
# This includes SMTP, Twilio, SMS, Payment, Webhook, SparkApiUrl, and background job settings.
$runtimeTransform = @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="RunJobsInIISContext" value="False" />
    <add key="PrTestEnvironment" value="True" />
    <add key="PrNumber" value="$PrNumber" />
    <add key="LogPath" value="$(Join-Path $EnvironmentPath "Logs")" />
    <add key="TempPath" value="$(Join-Path $EnvironmentPath "Temp")" />
    <add key="SharedFileStorageRoot" value="$SharedFileStorageRoot" />
    <add key="SMTPServer" value="localhost" />
    <add key="SMTPUserName" value="" />
    <add key="SMTPPassword" value="" />
    <add key="TwilioAccountSid" value="" />
    <add key="TwilioAuthToken" value="" />
    <add key="SMSProvider" value="Disabled" />
    <add key="PaymentGatewayMode" value="SandboxDisabled" />
    <add key="WebhookDeliveryEnabled" value="False" />
    <add key="SparkApiUrl" value="" />
  </appSettings>
</configuration>
"@
$runtimeTransform | Out-File -FilePath (Join-Path $SitePath "web.PrTestEnvironment.config") -Encoding UTF8 -Force

$runtimeState = [ordered]@{
    prNumber = $PrNumber
    sandboxConnectionConfig = "web.ConnectionStrings.config"
    runtimeConfig = "web.PrTestEnvironment.config"
    runJobsInIisContext = $false
    sharedFileStorageRoot = $SharedFileStorageRoot
    logPath = (Join-Path $EnvironmentPath "Logs")
    tempPath = (Join-Path $EnvironmentPath "Temp")
    externalIntegrations = "disabled-or-sandboxed"
    generatedAtUtc = (Get-Date).ToUniversalTime().ToString("o")
}
$runtimeState | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $SitePath "App_Data\PrTestEnvironment.json") -Encoding UTF8 -Force

Write-Host "Wrote sandbox runtime configuration for PR $PrNumber to $SitePath."
