<#
.SYNOPSIS
Writes sandbox-safe runtime configuration for a PR test environment.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [int]
    $PrNumber,

    [Parameter(Mandatory = $true)]
    [string]
    $SitePath,

    [Parameter(Mandatory = $true)]
    [string]
    $EnvironmentPath,

    [Parameter(Mandatory = $true)]
    [string]
    $SandboxConnectionString,

    [Parameter(Mandatory = $false)]
    [string]
    $SharedFileStorageRoot = "C:\RockTestEnvs\SharedStorage"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (!(Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

Ensure-Directory -Path $SitePath
Ensure-Directory -Path (Join-Path $SitePath "App_Data")
Ensure-Directory -Path (Join-Path $EnvironmentPath "Logs")
Ensure-Directory -Path (Join-Path $EnvironmentPath "Temp")
Ensure-Directory -Path $SharedFileStorageRoot

$connectionStringConfig = @"
<!-- Rock RMS PR test environment connection strings. Generated by Set-PrEnvironmentRuntimeConfiguration.ps1. -->
<connectionStrings>
  <add name="RockContext" connectionString="$SandboxConnectionString" providerName="System.Data.SqlClient" />
</connectionStrings>
"@
$connectionStringConfig | Out-File -FilePath (Join-Path $SitePath "web.ConnectionStrings.config") -Encoding UTF8 -Force

# No web.config rewrite for PublicApplicationRoot. This block used to read
# web.config, replace an <attributeValue attributeKey="PublicApplicationRoot">
# element, and write the file back. That element does not exist in
# RockWeb/web.config, so the replace matched nothing and the block's only real
# effect was rewriting the file it had just read.
#
# The value is a Rock global attribute held in the database. Note that a PR
# environment cannot have its own: the pr-* sites share one catalog by design,
# and a global attribute is one row per catalog, so a single value cannot be
# right for pr-1 and pr-2 at once. Per-environment public roots were what this
# block was reaching for, and they are not reachable this way.

# Production integration credentials are intentionally not deployed to PR environments.
# The transform below overrides common outbound integration/app settings with inert values.
# This includes SMTP, Twilio, SMS, Payment, Webhook, SparkApiUrl, and background job settings.
$runtimeTransform = @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="RunJobsInIISContext" value="False" />
    <add key="PrTestEnvironment" value="True" />
    <add key="PrNumber" value="$PrNumber" />
    <add key="LogPath" value="$(Join-Path $EnvironmentPath "Logs")" />
    <add key="TempPath" value="$(Join-Path $EnvironmentPath "Temp")" />
    <add key="SharedFileStorageRoot" value="$SharedFileStorageRoot" />
    <add key="SMTPServer" value="localhost" />
    <add key="SMTPUserName" value="" />
    <add key="SMTPPassword" value="" />
    <add key="TwilioAccountSid" value="" />
    <add key="TwilioAuthToken" value="" />
    <add key="SMSProvider" value="Disabled" />
    <add key="PaymentGatewayMode" value="SandboxDisabled" />
    <add key="WebhookDeliveryEnabled" value="False" />
    <add key="SparkApiUrl" value="" />
  </appSettings>
</configuration>
"@
$runtimeTransform | Out-File -FilePath (Join-Path $SitePath "web.PrTestEnvironment.config") -Encoding UTF8 -Force

$runtimeState = [ordered]@{
    prNumber = $PrNumber
    sandboxConnectionConfig = "web.ConnectionStrings.config"
    runtimeConfig = "web.PrTestEnvironment.config"
    runJobsInIisContext = $false
    sharedFileStorageRoot = $SharedFileStorageRoot
    logPath = (Join-Path $EnvironmentPath "Logs")
    tempPath = (Join-Path $EnvironmentPath "Temp")
    externalIntegrations = "disabled-or-sandboxed"
    generatedAtUtc = (Get-Date).ToUniversalTime().ToString("o")
}
$runtimeState | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $SitePath "App_Data\PrTestEnvironment.json") -Encoding UTF8 -Force

Write-Host "Wrote sandbox runtime configuration for PR $PrNumber to $SitePath."
